### ISSUE TITLE
Wait so it only runs once?

### ISSUE THREAD

**Issue by vyder** [arnavkohli/vaccine-availability-telegram-notifier#1]
Why not set it up to ping every X minutes so that it is actually useful?

It looks like you were trying to make a flask app but pivoted to just the script instead? Or am I reading too much into the unused code?

Otherwise you may as well output the result to the terminal instead of hooking it up to a Telegram bot

**Comment by arnavkohli** [comment]
Yes, the script (_script.py_) only runs once.

Feel free to run it as a CRON job at your desired interval with your configs. 

The **svc** module, which encompasses the flask API, holds the code for the registration service which is used by the Telegram bot @ https://t.me/KohlGuysBot.
